=== odieste/ejemplo-procesamiento-knitr-latex/XML-related-files/dataframe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://grise.upm.es/2021/R/dataframe" elementFormDefault="qualified">

  <xs:element name="dataframe">
    <xs:annotation>
      <xs:documentation>A dataframe is an unbounded sequence of columns. A dataframe without columns is possible.</xs:documentation>
    </xs:annotation>

    <xs:complexType>

      <xs:sequence>

        <xs:element name="column" minOccurs="0" maxOccurs="unbounded">
          <xs:annotation>
            <xs:documentation>A column has a type and is made of values. Zero values are possible.</xs:documentation>
          </xs:annotation>

          <xs:complexType>

            <xs:sequence>
              <xs:element name="value" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            
            <xs:attribute name="name" type="xs:string" use="required"/>

            <xs:attribute name="type">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="nominal"/>
                  <xs:enumeration value="ordinal"/>
                  <xs:enumeration value="interval"/>
                  <xs:enumeration value="ratio"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>

          </xs:complexType>
        </xs:element>

      </xs:sequence>

      <xs:attribute name="name" type="xs:string" use="required"/>
      
    </xs:complexType>
  </xs:element>

</xs:schema>

=== odieste/ejemplo-procesamiento-knitr-latex/XML-related-files/dataframe.xml
<?xml version="1.0"?>
<dataframe xmlns="http://grise.upm.es/2021/R/dataframe" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="expData" xsi:schemaLocation="http://grise.upm.es/2021/R/dataframe http://grise.upm.es/dataframe.xsd">
  <column name="STRATEGY" type="nominal">
    <value>MR</value>
    <value>MR</value>
    <value>MR</value>
    <value>BSK</value>
    <value>BSK</value>
    <value>BSK</value>
    <value>SS</value>
    <value>SS</value>
    <value>SS</value>
  </column>
  <column name="GROUP" type="ordinal">
    <value>G1</value>
    <value>G2</value>
    <value>G3</value>
    <value>G1</value>
    <value>G2</value>
    <value>G3</value>
    <value>G1</value>
    <value>G2</value>
    <value>G3</value>
  </column>
  <column name="Productivity" type="ratio">
    <value>14.1</value>
    <value>18.3</value>
    <value>21.0</value>
    <value>35.5</value>
    <value>44.4</value>
    <value>50.1</value>
    <value>3.2</value>
    <value>5.3</value>
    <value>7.7</value>
  </column>
</dataframe>
